// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxY-r5LlrMbFEx1LRcFKGextTdwUTBbCE',
    appId: '1:396966536210:web:a4c01f9bde3326717864cb',
    messagingSenderId: '396966536210',
    projectId: 'app-baby-shop-hub',
    authDomain: 'app-baby-shop-hub.firebaseapp.com',
    storageBucket: 'app-baby-shop-hub.appspot.com',
    measurementId: 'G-DY2TBGYQP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuj1eXqT_DbQfm5bTHA0K520kgOLBPkU',
    appId: '1:396966536210:android:c773f6ab8deb25057864cb',
    messagingSenderId: '396966536210',
    projectId: 'app-baby-shop-hub',
    storageBucket: 'app-baby-shop-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXr8uYyV6BIqdZGYbdvk_Ke4ZyCkCQiPE',
    appId: '1:396966536210:ios:c7f09bb9279126ed7864cb',
    messagingSenderId: '396966536210',
    projectId: 'app-baby-shop-hub',
    storageBucket: 'app-baby-shop-hub.appspot.com',
    iosBundleId: 'com.example.appbabyshophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXr8uYyV6BIqdZGYbdvk_Ke4ZyCkCQiPE',
    appId: '1:396966536210:ios:c7f09bb9279126ed7864cb',
    messagingSenderId: '396966536210',
    projectId: 'app-baby-shop-hub',
    storageBucket: 'app-baby-shop-hub.appspot.com',
    iosBundleId: 'com.example.appbabyshophub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxY-r5LlrMbFEx1LRcFKGextTdwUTBbCE',
    appId: '1:396966536210:web:58a3ec86a5f1770d7864cb',
    messagingSenderId: '396966536210',
    projectId: 'app-baby-shop-hub',
    authDomain: 'app-baby-shop-hub.firebaseapp.com',
    storageBucket: 'app-baby-shop-hub.appspot.com',
    measurementId: 'G-VR5KPX36Q4',
  );
}
